In [5]:
#difference in list and array
list = [[20,30],[50,40,60]]
print(list)#success


'''#but in array 
a = np.array([20,30],[50,40,60])
print(a)#error beacuse in array both list have 3 values are compulsory
'''

[[20, 30], [50, 40, 60]]


'#but in array \na = np.array([20,30],[50,40,60])\nprint(a)#error beacuse in array both list have 3 values are compulsory\n'

In [2]:
import numpy as np
a = np.array([23,45,39])
b = np.array([40,20,30])
print(a)
print(a+b)

[23 45 39]
[63 65 69]


In [38]:
#matrix
m = np.array([10,20,30,40],[15,25,35,45],[50,60,70,80],[55,65,75,85])
print(m)
print(np.shape(m))
print(np.size(m))

#slicing of array
a = np.array([20,30,40,50])
print(a[0:3])



TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [24]:
#slicing of array with multiple list
a = np.array([[10,20,30,40],[15,25,35,45]])
print(a[0:3,0:3])
print(a[0:2,0:3])
print(a[0:3,0:2])
print(np.shape(a))


[[10 20 30]
 [15 25 35]]
[[10 20 30]
 [15 25 35]]
[[10 20]
 [15 25]]
(2, 4)


In [40]:
#inspecting an array
arr = [[10,20,30],[15,25,35]]
m = np.array(arr)
#to check row and column
print(m.shape)
#to chheck size
print(m.size)
print(np.size(m))
#to check datatype of array
print(m.dtype)
#to change type
print(m.astype(str))


(2, 3)
6
6
int32
[['10' '20' '30']
 ['15' '25' '35']]


In [47]:
#mathematical operations on array
a = np.array([[30,10],[20,10]])
b = np.array([[30,20],[50,10]])
#add
print(np.add(a,b))
#subtract
print(np.subtract(a,b)) #or print(a-b)
#multiply
print(np.multiply(a,b))#or print(a*b)
#divide
print(np.divide(a,b))#or print(a/b)

[[60 30]
 [70 20]]
[[  0 -10]
 [-30   0]]
[[ 900  200]
 [1000  100]]
[[1.  0.5]
 [0.4 1. ]]


In [52]:
#find power 
arr = np.array([3,5,7,2])
arr1 = np.array([2])
print(np.power(arr,arr1))

#find square root
a = np.array([9,25,49,4])
print(np.sqrt(a))

[ 9 25 49  4]
[3. 5. 7. 2.]


In [56]:
#concatenate(join two arrays)
arr1 = np.array([15,25,35])
arr2 = np.array([1,2,3])
print(np.concatenate([arr1,arr2]))

[15 25 35  1  2  3]


In [59]:
#concatenate(join two arrays)
arr1 = np.array([[15,25],[35,45]])
arr2 = np.array([[1,2],[3,3]])
print(np.concatenate([arr1,arr2],axis = 1))

[[15 25  1  2]
 [35 45  3  3]]


In [61]:
#horizontal concatenate
arr1 = np.array([[15,25],[35,45]])
arr2 = np.array([[1,2],[3,3]])
print(np.hstack([arr1,arr2]))
#vertically concatenate
print(np.vstack([arr1,arr2]))

[[15 25  1  2]
 [35 45  3  3]]
[[15 25]
 [35 45]
 [ 1  2]
 [ 3  3]]


In [67]:
arr1 = np.array([15,25,35,45])
a = np.array_split(arr1[2])

TypeError: array_split() missing 1 required positional argument: 'indices_or_sections'

In [8]:
import numpy as np
#adding and removing elements from numpy array
a = np.array([20,40,60,80])
print(np.append(a,[90]))
print(np.insert(a,1,50))
print(np.delete(a,1))

[20 40 60 80 90]
[20 50 40 60 80]
[20 60 80]


In [14]:
#search_sort_filter on numpy array
#sort the array
import numpy as np
a = np.array([[34,2,7,1,13],[42,6,14,24,7]])
print(np.sort(a))

[[ 1  2  7 13 34]
 [ 6  7 14 24 42]]


In [17]:
#search in the numpy array
a = np.array([[34,2,7,1,13],[42,6,14,24,7]])
s = np.where(a%2 == 0)
print(s)

(array([0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 0, 1, 2, 3], dtype=int64))


In [22]:
#filter in numpy array
import numpy as np
a = np.array([34,6,18,9,17])
fa = [True, False, True, False, False]
new = a[fa]
print(new)
#both  a and fa have same number of values.
fa = a<=15
new = a[fa]
print(new)


[34 18]
[6 9]


In [27]:
#aggregation function
import numpy as np
a = np.array([34,6,18,9,17])
print(np.sum(a))
print(np.min(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.max(a))

84
6
16.8
[34 40 58 67 84]
34


In [44]:
"""aggregation function on numpy array to check the 
final price of products
"""
import numpy as np
a = np.array([100,150,170,230,200,140])
b = np.array([7,4,2,9,5,3])
price = np.array(a)
quantity=(np.array(b))
print(price ,"\n",quantity)
#apply aggregate product
#if we have two columns then it is compulsory to pass axis
c = np.cumprod([price,quantity], axis = 0)
print(c[1])
print(c[1].sum())

[100 150 170 230 200 140] 
 [7 4 2 9 5 3]
[ 700  600  340 2070 1000  420]
5130


In [51]:
#statistical function
import numpy as np
#for mode
import statistics as stats
a = np.array([100,150,170,230,100,200,140])
#find the mean
print(np.mean(a))#sum of all values/number of values
#find the median
print(np.median(a))#after sorting an array the central value is mediaan
#find mode
'''in numpy there is no any function of mode thats why
we use "stats" to find mode
mode is the number which reuccure
we have to import : import statistics as stats'''
print(stats.mode(a))
print(np.std(a))#check the standard deviation
print(np.var(a))#variation is the square root of SD

155.71428571428572
150.0
100
44.99433070863892
2024.489795918367


In [55]:
#co-relation
'''-1 represents inversly proportional relationship
1 reprents proportional relationship
0 reprents neutral doesnt depend on each other'''
#example
'''in this example the value is between 0 to 1 which means 
value of death increases acc to tobacco cunsumption'''
import numpy as np
tobacco_cunsumption = np.array([30,50,10,40,60])
deaths = np.array([100,150,40,140,156])
print(np.corrcoef([tobacco_cunsumption,deaths]))
#example2
'''in this example the value is between -1 to 0 which means 
sales decrease when price increase'''
price = np.array([200,100,350,150,300])
sales = np.array([15,24,10,20,12])
print(np.corrcoef([price,sales]))

[[1.         0.96525442]
 [0.96525442 1.        ]]
[[ 1.         -0.97085578]
 [-0.97085578  1.        ]]
